spring.datasource.url=jdbc:postgresql://localhost:5432/newDb
spring.datasource.username=postgres
spring.datasource.password=Deadpool13
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=rate-limiting-bucket4j-spring-boot
spring.data.rest.base-path=/api
server.port=8081



# Mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pracownik298@gmail.com
spring.mail.password=ypke fxnf anyt eogj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
